### ISSUE TITLE
File cannot be processed if it does not have at least one "Shared Storage" item

### ISSUE THREAD

**Issue by G-Rath** [IowaComputerGurus/github-cost-visualizer#18]
As the title says - I downloaded a 7 day usage report that didn't have a line item for "Shared Storage" and the visualizer would report it was unable to process the file; once I copied and pasted in a line for "Shared Storage" from a 30 day report, it was able to use the 7 day report without issue.

Let me know if you need anymore details, or are not able to reproduce the error.

**Comment by mitchelsellers** [comment]
We will get this fixed

**Comment by G-Rath** [comment]
Thanks! I'd be happy to help, except C# is one of the only main languages I don't do anything with 😅

**Comment by mitchelsellers** [comment]
@G-Rath we are deploying an update now that fixes this.  Will make a larger update soon
