### ISSUE TITLE
feature request: actions spending

### ISSUE THREAD

**Issue by jinzishuai** [IowaComputerGurus/github-cost-visualizer#20]
Great tool.

I have two feature suggestions:
1. Provide a way to switch between minutes and dollars to view the Github Actions spending.
2. Similar to the storage chart by day analysis, provide an analysis on minutes breakdown by days. 

Thank you so much.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1091929445) by [Unito](https://www.unito.io)

**Comment by mitchelsellers** [comment]
Great suggestions, I've added this to our listing for future implementation.
