### ISSUE TITLE
Unable to process empty files

### ISSUE THREAD

**Issue by G-Rath** [IowaComputerGurus/github-cost-visualizer#25]
It seems the app cannot handle a usage report that has just the header, i.e.

【 code  】
Date,Product,SKU,Quantity,Unit Type,Price Per Unit ($),Multiplier,Owner,Repository Slug,Username,Actions Workflow,Notes

【 end code 】

While such a report obviously is of little use I think it would be best for the app to handle it gracefully

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1221891008) by [Unito](https://www.unito.io)

**Comment by mitchelsellers** [comment]
Thanks for this report, we will look at this.

Just to confirm you are looking at a usage report with NO usage reported correct

**Comment by G-Rath** [comment]
Correct - this is the original file: [0920484b_2023-10-01_7.csv](https://github.com/IowaComputerGurus/github-cost-visualizer/files/12778101/0920484b_2023-10-01_7.csv)

(I forgot I can just drop it in here when I opened the ticket 😅)
