### ISSUE TITLE
Show pricing per repository

### ISSUE THREAD

**Issue by G-Rath** [IowaComputerGurus/github-cost-visualizer#28]
It would be good to see the cost per repository in addition to the total - I feel like this could easily be added as a third column to the minutes and storage tables

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1234433106) by [Unito](https://www.unito.io)

**Comment by mitchelsellers** [comment]
This is a great idea, let me look at this!

**Comment by mitchelsellers** [comment]
In looking at this we will be updating the reporting for `List (By Repo)` and `List (By Workflow)` to include an `Estimated Cost` column to visualize how the individual repositories contribute to the total estimated costs.
