### ISSUE TITLE
Github Actions: sum of minutes per workflow file

### ISSUE THREAD

**Issue by staabm** [IowaComputerGurus/github-cost-visualizer#29]
would be great to see which particular workflow file produces the most github action minutes accumulated over the whole report.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1262732253) by [Unito](https://www.unito.io)

**Comment by mitchelsellers** [comment]
@staabm This was a great idea!!  I just implemented this and the website https://www.githubcostvisualizer.com should be updated in about 20 minutes!

**Comment by staabm** [comment]
nice, thank you
