### ISSUE TITLE
Github Cost Visualizer unable to process file

### ISSUE THREAD

**Issue by Filip-Labarque** [IowaComputerGurus/github-cost-visualizer#9]
When downloading a usage report of the last 30 days from GitHub and uploading it to the Github Cost Visualizer, it returns this error: "Unable to process file, please ensure the file is un-modified from GitHub.". While I did not modify the file from GitHub.

**Comment by mitchelsellers** [comment]
Any possibility you could send me a copy of the file?  Msellers@iowacomputergurus . Com

I just validated with our export file this AM, so curious to see if you have a difference in file.

**Comment by Filip-Labarque** [comment]
Done, I've sent you the file.

**Comment by mitchelsellers** [comment]
@Filip-Labarque Thank you for sending this in.

I've identified the root cause and the website will be updated in about 20 minutes with a fix in place!
